SELECT 
  COUNT_IF(ORDER_ID IS NULL) AS missing_order_id,
  COUNT_IF(LOCATION_ID IS NULL) AS missing_location_id,
  COUNT_IF(GUEST_ID IS NULL) AS missing_guest_id,
  COUNT_IF(ORDER_CREATED_AT_PT IS NULL) AS missing_created_at,
  COUNT_IF(GMV IS NULL) AS missing_gmv
FROM DEMO_DB.PUBLIC.PRODUCT_ANALYTICS_CASE_V2

SELECT ORDER_ID, COUNT(*) 
FROM DEMO_DB.PUBLIC.PRODUCT_ANALYTICS_CASE_V2
GROUP BY ORDER_ID
HAVING COUNT(*) > 1;

SELECT COUNT(*) 
FROM DEMO_DB.PUBLIC.PRODUCT_ANALYTICS_CASE_V2
WHERE DELIVERY_TYPE IS NOT NULL AND ORDER_TYPE != 'delivery';

select 
order_type,
delivery_type,
count(1)
from DEMO_DB.PUBLIC.PRODUCT_ANALYTICS_CASE_V2
group by 1,2

SELECT 
  PERCENTILE_CONT(0.99) WITHIN GROUP (ORDER BY GMV) AS p99_gmv,
  MAX(GMV) AS max_gmv,
  AVG(GMV) AS avg_gmv
FROM DEMO_DB.PUBLIC.PRODUCT_ANALYTICS_CASE_V2

SELECT count(1)
FROM DEMO_DB.PUBLIC.PRODUCT_ANALYTICS_CASE_V2

SELECT 
  COUNT_IF(GMV <= 0) AS invalid_gmv,
  COUNT_IF(NUMBER_OF_ITEMS <= 0) AS invalid_items,
  COUNT_IF(DELIVERY_FEE < 0) AS negative_delivery_fee
FROM DEMO_DB.PUBLIC.PRODUCT_ANALYTICS_CASE_V2;

select *
from DEMO_DB.PUBLIC.PRODUCT_ANALYTICS_CASE_V2
where GMV <= 0

SELECT ORDER_SOURCE, DELIVERY_TYPE, 
       MIN(ORDER_CREATED_AT_PT) AS first_date, 
       MAX(ORDER_CREATED_AT_PT) AS last_date, 
       COUNT(*) AS invalid_orders
FROM DEMO_DB.PUBLIC.PRODUCT_ANALYTICS_CASE_V2
WHERE GMV <= 0
GROUP BY 1,2
ORDER BY invalid_orders DESC

select *
from DEMO_DB.PUBLIC.PRODUCT_ANALYTICS_CASE_V2
where NUMBER_OF_ITEMS <= 0
